# **Summer Training First Hackathon**

# Loading the dataset from kaggle

In [ ]:
import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, classification_report, roc_auc_score,auc,roc_curve

In [ ]:
data = pd.read_csv('hacktrain.csv')
test_data = pd.read_csv('hacktest.csv')

**Defining Random Seed**

In [ ]:
Random_State = 42
np.random.seed(Random_State)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8000 non-null   int64
 1   ID          8000 non-null   int64
 2   class       8000 non-null   object
 3   20150720_N  7440 non-null   float64
 4   20150602_N  6800 non-null   float64
 5   20150517_N  7200 non-null   float64
 6   20150501_N  7040 non-null   float64
 7   20150415_N  7520 non-null   float64
 8   20150330_N  6880 non-null   float64
 9   20150314_N  7280 non-null   float64
 10  20150226_N  6640 non-null   float64
 11  20150210_N  7360 non-null   float64
 12  20150125_N  6960 non-null   float64
 13  20150109_N  7120 non-null   float64
 14  20141117_N  6720 non-null   float64
 15  20141101_N  7600 non-null   float64
 16  20141016_N  6560 non-null   float64
 17  20140930_N  7200 non-null   float64
 18  20140813_N  7440 non-null   float64
 19  20140626_N  6400 non-null   float64
 20  20140610_N  7520 non-null   float64
 21  20140525_N  7280 non-null   float64
 22  20140509_N  7120 non-null   float64
 23  20140423_N  6240 non-null   float64
 24  20140407_N  7360 non-null   float64
 25  20140322_N  6880 non-null   float64
 26  20140218_N  6560 non-null   float64
 27  20140202_N  7440 non-null   float64
 28  20140117_N  6800 non-null   float64
 29  20140101_N  7600 non-null   float64
dtypes: float64(27), int64(2), object(1)
memory usage: 1.8+ MB

In [ ]:
data.sample(10)

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
2215,2776,2777,forest,NaN,7755.640,6955.480,2275.80,7329.220,7474.68,3961.580,...,5762.360,6725.27,NaN,132.350,3528.640,5342.110,4969.25,7601.13,NaN,906.499
2582,3226,3227,forest,NaN,8218.030,5965.590,5014.90,7803.670,3713.92,2206.760,...,6367.540,4469.14,NaN,408.579,1843.290,5176.100,NaN,7910.58,7900.230,2916.730
1662,2108,2109,forest,NaN,6554.260,5517.160,6705.12,5301.180,7638.14,4679.270,...,8177.470,6321.72,4220.980,4901.600,1985.580,418.154,NaN,7313.60,NaN,945.712
3027,3754,3755,forest,NaN,6230.480,779.933,6424.40,318.335,3870.53,2377.250,...,6947.160,6415.91,2693.620,NaN,885.813,6658.280,NaN,NaN,2581.750,1113.920
4343,5325,5326,forest,NaN,1117.140,6511.560,2079.74,7390.080,6735.03,2318.850,...,7775.500,6962.56,393.632,1526.000,409.319,7272.310,2243.40,7257.04,670.491,NaN
2680,3342,3343,forest,NaN,NaN,1098.280,3553.48,4259.990,6655.82,1409.230,...,7267.380,4440.67,3346.010,NaN,5236.150,629.142,2759.81,NaN,2073.810,3209.930
1765,2229,2230,forest,NaN,7125.440,8163.290,7698.42,2579.910,4931.21,5146.900,...,8284.660,3926.21,4969.390,724.654,2036.010,753.738,7984.82,7896.94,NaN,2056.360
1123,1434,1435,forest,NaN,NaN,3717.340,6998.47,6477.370,3929.32,7088.580,...,8090.480,6916.95,NaN,5717.690,6988.740,1170.220,7410.85,8004.82,4480.420,752.044
4054,4979,4980,forest,NaN,921.743,5243.540,5553.06,403.323,2252.18,670.471,...,4396.360,NaN,604.255,NaN,414.730,453.767,NaN,7252.02,407.413,NaN
3761,4623,4624,forest,NaN,7826.550,8210.580,8176.95,194.104,5510.96,4608.890,...,982.965,4863.74,1117.080,NaN,321.510,6741.480,954.32,7120.85,487.236,2435.700

# Data Preprocessing

In [ ]:
data.isnull().sum()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64

**Imputing the null values**

In [ ]:
data.fillna(data.mean(numeric_only=True), inplace=True)
data.isnull().sum()

Unnamed: 0    0
ID            0
class         0
20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
dtype: int64

**dropping unnecessary features**

In [ ]:
data = data.drop(['Unnamed: 0','ID'],axis=1)

In [ ]:
data.head(5)

,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,water,637.5950,658.668000,-1882.030000,-1924.36,997.904000,-1739.990000,630.087000,4987.520158,-1325.64,...,4872.68167,-1043.160,-1942.490000,267.138,2041.316792,2799.820342,211.328,-2203.020,-1180.190000,433.906
1,water,634.2400,593.705000,-1625.790000,-1672.32,914.198000,-692.386000,707.626000,-1670.590000,-1408.64,...,4872.68167,-933.934,-625.385000,120.059,364.858000,476.972000,220.878,-2250.000,-1360.560000,524.075
2,water,58.0174,-1599.160000,4469.837748,-1052.63,2927.586705,-1564.630000,3313.881373,729.790000,-3162.14,...,-1025.88000,368.622,3012.178524,-1227.800,304.621000,2799.820342,369.214,-2202.120,2629.203972,-1343.550
3,water,72.5180,4868.091395,380.436000,-1256.93,515.805000,-1413.180000,-802.942000,683.254000,-2829.40,...,-1813.95000,155.624,3012.178524,-924.073,432.150000,282.833000,298.320,-2197.360,2629.203972,-826.727
4,water,1136.4400,4868.091395,4469.837748,1647.83,1935.800000,4924.493648,2158.980000,4987.520158,1242.87,...,1535.00000,1959.430,-279.317000,-384.915,-113.406000,1020.720000,1660.650,-116.801,-568.050000,-1357.140

# Label encoding for target variable

In [ ]:
LE = LabelEncoder()
data['class'] = LE.fit_transform(data['class'])
print(LE.classes_)

['farm' 'forest' 'grass' 'impervious' 'orchard' 'water']

# Splitting

In [ ]:
x = data.drop('class',axis=1)
y = data['class']

x.shape, y.shape

((8000, 27), (8000,))

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=Random_State, stratify=y)

print(f"size of x_train : {x_train.shape}")
print(f"size of x_test : {x_test.shape}")
print(f"size of y_train : {y_train.shape}")
print(f"size of y_test : {y_test.shape}")

size of x_train : (6400, 27)
size of x_test : (1600, 27)
size of y_train : (6400,)
size of y_test : (1600,)

# scaling the x_train and x_test

In [ ]:
scaler = StandardScaler()
x_train_scaled = pd.DataFrame(scaler.fit_transform(x_train),columns=x.columns)
x_test_scaled = pd.DataFrame(scaler.transform(x_test),columns=x.columns)
x_train_scaled.head()

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0.143581,1.130508,-1.077382,0.665453,1.494216,-0.738927,1.092696,1.003326,1.195558,0.892907,...,1.115040,1.151393,0.380499,-0.002052,2.462860,-0.957489,0.002485,0.005057,1.951064,-0.806698
1,0.887777,-0.833417,0.550181,1.251768,-0.998975,1.067889,0.768542,-0.008006,-1.227202,-1.849480,...,-1.610141,0.585804,-1.200652,2.204549,-0.868183,2.179840,-0.757875,0.433119,-1.017416,-0.450596
2,0.937136,-0.558213,0.905716,1.327893,-0.979320,-1.842694,-1.114115,-0.645289,-1.300870,-1.711207,...,-0.100052,-1.278921,2.663662,-1.150285,-0.890458,-1.002941,-0.852462,0.483787,-0.984563,-0.851179
3,0.721301,1.078454,-1.465210,0.902169,1.754419,1.174419,-0.693198,1.134519,-1.359394,1.033368,...,0.793605,1.449606,-0.003144,-0.528653,-0.910403,2.140871,-0.621823,0.005057,-0.243698,2.203547
4,0.641917,1.108154,-0.157706,-0.002263,-0.855811,-1.099196,0.586241,-1.430722,-1.260267,0.007263,...,1.017400,0.678949,-1.276438,1.779195,2.453251,-0.995927,1.483081,0.343073,-0.552418,1.518653

In [ ]:
LR = LogisticRegression(random_state=Random_State,
                        multi_class = 'multinomial',
                        solver = 'lbfgs',
                        max_iter = 20)
model_1 = LR.fit(x_train_scaled,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
pred_1 = model_1.predict(x_test_scaled)

accuracy_1 = accuracy_score(y_test,pred_1)
print(f"Accuracy of model_1 : {accuracy_1:.2f}\n")
print(classification_report(y_test,pred_1))

Accuracy of model_1 : 0.87

              precision    recall  f1-score   support

           0       0.63      0.38      0.47       168
           1       0.90      0.97      0.93      1232
           2       0.35      0.15      0.21        39
           3       0.83      0.84      0.83       134
           4       1.00      0.17      0.29         6
           5       0.79      0.52      0.63        21

    accuracy                           0.87      1600
   macro avg       0.75      0.50      0.56      1600
weighted avg       0.85      0.87      0.85      1600

# test_data

In [ ]:
test_data

,Unnamed: 0,ID,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,7466.4200,413.162,5761.000,5625.45,489.4030,3923.84,3097.110,6766.42000,...,801.184,927.115,4704.14,6378.42,340.949,2695.5700,527.268,4736.75,601.843,6639.760
1,1,2,7235.2600,6037.350,1027.560,6085.14,1618.0500,6668.54,2513.990,1051.69000,...,5533.470,5103.040,5216.12,4885.27,4366.790,1234.1400,3298.110,6942.68,1070.440,842.101
2,2,3,7425.0800,6969.980,1177.940,7408.93,861.0610,7644.43,814.458,1504.29000,...,1981.390,6204.540,7021.69,5704.41,4897.450,1789.9900,2206.100,6928.93,1036.560,831.441
3,3,4,7119.1200,1731.620,6311.930,6441.61,465.9790,7128.42,1649.120,6935.22000,...,959.344,5794.150,1045.57,5572.90,586.287,685.9060,1287.000,6734.72,824.584,6883.610
4,4,5,7519.5500,8130.260,1482.540,7879.53,1001.2100,7937.60,4122.530,1094.51000,...,7636.070,6996.760,7413.43,4596.13,4511.700,1413.5200,3283.940,7937.68,1857.800,1336.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,2840,2841,-1673.7400,-2514.480,-2451.190,-2738.44,64.4464,-2275.03,-2881.100,-4738.97000,...,-2257.890,-2582.420,-1699.10,-2295.30,306.483,209.4030,221.920,-4885.15,-2630.590,356.233
2841,2841,2842,-96.8233,-412.727,-1795.400,-2363.82,-2168.1900,-2162.68,-3155.740,-4416.11000,...,-3991.910,-2614.910,-2109.84,-2687.18,-2853.890,71.3402,-86.414,-5109.01,324.637,-4316.580
2842,2842,2843,-2364.6000,-155.592,-1422.090,-1713.40,465.6220,-2230.40,-3088.730,-5010.32000,...,-2484.500,-1756.080,-3820.43,-1988.23,433.852,291.8000,254.548,-4259.30,412.115,-1170.750
2843,2843,2844,-3004.6300,-1217.120,180.122,-1113.89,438.4180,-2442.51,-3210.560,-3237.74000,...,-3291.490,-2018.450,-3472.65,-3109.07,511.792,369.0970,276.948,-5574.51,298.739,460.419
2844,2844,2845,-2975.1000,-1129.790,463.748,-5355.40,193.5110,-2590.16,-3113.520,-2.38883,...,-3058.230,-2276.180,-3335.00,-2929.19,-1007.500,271.0580,307.997,-5453.33,307.495,417.124

In [ ]:
test_data.isnull().sum()

Unnamed: 0    0
ID            0
20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
dtype: int64

# making test_data to fit in model

In [ ]:
test_data_1 = test_data.copy()

In [ ]:
test_data_1 = test_data.drop(['Unnamed: 0','ID'],axis=1)
test_data_1

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,7466.4200,413.162,5761.000,5625.45,489.4030,3923.84,3097.110,6766.42000,2829.130,6742.570,...,801.184,927.115,4704.14,6378.42,340.949,2695.5700,527.268,4736.75,601.843,6639.760
1,7235.2600,6037.350,1027.560,6085.14,1618.0500,6668.54,2513.990,1051.69000,7268.220,6908.180,...,5533.470,5103.040,5216.12,4885.27,4366.790,1234.1400,3298.110,6942.68,1070.440,842.101
2,7425.0800,6969.980,1177.940,7408.93,861.0610,7644.43,814.458,1504.29000,7002.630,6086.560,...,1981.390,6204.540,7021.69,5704.41,4897.450,1789.9900,2206.100,6928.93,1036.560,831.441
3,7119.1200,1731.620,6311.930,6441.61,465.9790,7128.42,1649.120,6935.22000,2176.800,690.408,...,959.344,5794.150,1045.57,5572.90,586.287,685.9060,1287.000,6734.72,824.584,6883.610
4,7519.5500,8130.260,1482.540,7879.53,1001.2100,7937.60,4122.530,1094.51000,7951.440,8001.350,...,7636.070,6996.760,7413.43,4596.13,4511.700,1413.5200,3283.940,7937.68,1857.800,1336.920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,-1673.7400,-2514.480,-2451.190,-2738.44,64.4464,-2275.03,-2881.100,-4738.97000,-4293.570,-4402.210,...,-2257.890,-2582.420,-1699.10,-2295.30,306.483,209.4030,221.920,-4885.15,-2630.590,356.233
2841,-96.8233,-412.727,-1795.400,-2363.82,-2168.1900,-2162.68,-3155.740,-4416.11000,-5648.660,-5193.280,...,-3991.910,-2614.910,-2109.84,-2687.18,-2853.890,71.3402,-86.414,-5109.01,324.637,-4316.580
2842,-2364.6000,-155.592,-1422.090,-1713.40,465.6220,-2230.40,-3088.730,-5010.32000,-4211.420,-3354.430,...,-2484.500,-1756.080,-3820.43,-1988.23,433.852,291.8000,254.548,-4259.30,412.115,-1170.750
2843,-3004.6300,-1217.120,180.122,-1113.89,438.4180,-2442.51,-3210.560,-3237.74000,-192.857,-2857.540,...,-3291.490,-2018.450,-3472.65,-3109.07,511.792,369.0970,276.948,-5574.51,298.739,460.419
2844,-2975.1000,-1129.790,463.748,-5355.40,193.5110,-2590.16,-3113.520,-2.38883,-1248.450,328.306,...,-3058.230,-2276.180,-3335.00,-2929.19,-1007.500,271.0580,307.997,-5453.33,307.495,417.124

In [ ]:
test_data_scaled = pd.DataFrame(scaler.fit_transform(test_data_1), columns=test_data_1.columns)
test_data_scaled

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0.918275,-1.532337,0.631417,0.395182,-0.865244,-0.299493,-0.123145,0.784489,-0.413641,0.776577,...,-1.329982,-1.166912,0.815621,1.610416,-0.859878,0.156482,-0.628442,-0.342260,-0.799642,1.699348
1,0.820954,0.564099,-1.038087,0.575837,-0.413353,0.749188,-0.360614,-1.236168,1.213742,0.834721,...,0.432495,0.721635,1.064943,0.910147,1.220987,-0.502381,0.754735,0.571578,-0.589890,-0.697845
2,0.900870,0.911740,-0.985047,1.096078,-0.716439,1.122051,-1.052731,-1.076135,1.116376,0.546259,...,-0.890430,1.219784,1.944210,1.294313,1.495274,-0.251785,0.209615,0.565882,-0.605055,-0.702253
3,0.772057,-1.040877,0.825732,0.715928,-0.874623,0.924897,-0.712824,0.844175,-0.652787,-1.348272,...,-1.271077,1.034187,-0.966010,1.232637,-0.733069,-0.749544,-0.249191,0.485427,-0.699939,1.800174
4,0.940643,1.344238,-0.877613,1.281020,-0.660326,1.234064,0.294447,-1.221028,1.464213,1.218521,...,1.215581,1.578063,2.134977,0.774543,1.295888,-0.421510,0.747662,0.983770,-0.237453,-0.493249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,-2.929851,-2.623626,-2.265056,-2.891769,-1.035390,-2.667925,-2.557709,-3.283674,-3.024843,-3.136235,...,-2.469293,-2.754087,-2.302596,-2.457454,-0.877693,-0.964368,-0.780868,-4.328265,-2.246537,-0.898740
2841,-2.265949,-1.840190,-2.033756,-2.744546,-1.929300,-2.624999,-2.669553,-3.169515,-3.521623,-3.413971,...,-3.115106,-2.768780,-2.502616,-2.641241,-2.511218,-1.026611,-0.934786,-4.421002,-0.923724,-2.830836
2842,-3.220712,-1.744342,-1.902088,-2.488935,-0.874766,-2.650873,-2.642264,-3.379620,-2.994727,-2.768371,...,-2.553691,-2.380378,-3.335630,-2.313442,-0.811859,-0.927220,-0.764581,-4.068998,-0.884568,-1.530111
2843,-3.490173,-2.140030,-1.336981,-2.253332,-0.885658,-2.731915,-2.691878,-2.752858,-1.521510,-2.593918,...,-2.854244,-2.499033,-3.166270,-2.839102,-0.771574,-0.892372,-0.753399,-4.613842,-0.935317,-0.855662
2844,-3.477741,-2.107478,-1.236945,-3.920216,-0.983715,-2.788328,-2.652360,-1.608878,-1.908493,-1.475402,...,-2.767369,-2.615591,-3.099238,-2.754741,-1.556861,-0.936572,-0.737899,-4.563642,-0.931398,-0.873563

In [ ]:
pred_test = model_1.predict(test_data_scaled)
pred_test

array([1, 1, 4, ..., 5, 3, 3])

In [ ]:
test_class = LE.inverse_transform(pred_test)

In [ ]:
submission = pd.DataFrame()
submission['ID'] = test_data['ID']
submission['class'] = test_class
submission

        ID       class
0        1      forest
1        2      forest
2        3     orchard
3        4      forest
4        5      forest
...    ...         ...
2840  2841  impervious
2841  2842  impervious
2842  2843       water
2843  2844  impervious
2844  2845  impervious

[2845 rows x 2 columns]

In [ ]:
submission.to_csv('submission.csv',index=False)